spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ch03ex2;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always